### ISSUE TITLE
Disable unloading items

### ISSUE THREAD

**Issue by KarsusITA** [frankdiox/OnsenUI-LazyRepeat#1]
Hello.
I need that the directive doesn't unload the item out the display range.
I have few elements to load but the server is slow, so everytime I pop the page after a push on one of the last items of the list all the last items are destroyed.

Thank you

**Comment by frandiox** [comment]
LazyRepeat will always unload elements since that's its purpose (although perhaps this will change in Onsen UI updates soon). But that does not mean you need to create or retrieve the items over and over again. Just create them once and store them locally beforehand and tell LazyRepeat to use the stored values. If you want to create the items "on fly" with LazyRepeat, check first whether an item already exists locally. If does, use it. If doesn't, create and store it for the next time.

I hope you find this helpful :)
